version: '3.8'

services:
  app:
    build: .
    container_name: e-commerce-app
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    # Hot reload for development
    stdin_open: true
    tty: true
